"""Readicionando todo o banco de dados

Revision ID: 0e8b5e0f7fdf
Revises: 18b0d18bc24c
Create Date: 2025-03-25 19:41:00.942499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8b5e0f7fdf'
down_revision = '18b0d18bc24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('ed', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('ed', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_b')
    op.drop_table('livros_a')
    # ### end Alembic commands ###
