"""Adicionei os livros tanto do A e do B

Revision ID: 18b0d18bc24c
Revises: 42406fd3b97d
Create Date: 2025-03-09 19:03:08.791202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b0d18bc24c'
down_revision = '42406fd3b97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('ed', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('ed', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('livros')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fisica', sa.VARCHAR(), nullable=True),
    sa.Column('quimica', sa.VARCHAR(), nullable=True),
    sa.Column('biologia', sa.VARCHAR(), nullable=True),
    sa.Column('sociologia', sa.VARCHAR(), nullable=True),
    sa.Column('geografia', sa.VARCHAR(), nullable=True),
    sa.Column('filosofia', sa.VARCHAR(), nullable=True),
    sa.Column('historia', sa.VARCHAR(), nullable=True),
    sa.Column('matematica', sa.VARCHAR(), nullable=True),
    sa.Column('portugues', sa.VARCHAR(), nullable=True),
    sa.Column('ed', sa.VARCHAR(), nullable=True),
    sa.Column('ingles', sa.VARCHAR(), nullable=True),
    sa.Column('literatura', sa.VARCHAR(), nullable=True),
    sa.Column('artes', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('livros_b')
    op.drop_table('livros_a')
    # ### end Alembic commands ###
