"""first migrate

Revision ID: 42406fd3b97d
Revises: 
Create Date: 2025-03-09 17:40:36.638422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42406fd3b97d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('ed', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros')
    # ### end Alembic commands ###
