"""first migrate

Revision ID: a21c474fc2a0
Revises: 
Create Date: 2025-04-05 15:26:44.480600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21c474fc2a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('educacao', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livros_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fisica', sa.String(), nullable=True),
    sa.Column('quimica', sa.String(), nullable=True),
    sa.Column('biologia', sa.String(), nullable=True),
    sa.Column('sociologia', sa.String(), nullable=True),
    sa.Column('geografia', sa.String(), nullable=True),
    sa.Column('filosofia', sa.String(), nullable=True),
    sa.Column('historia', sa.String(), nullable=True),
    sa.Column('matematica', sa.String(), nullable=True),
    sa.Column('portugues', sa.String(), nullable=True),
    sa.Column('educacao', sa.String(), nullable=True),
    sa.Column('ingles', sa.String(), nullable=True),
    sa.Column('literatura', sa.String(), nullable=True),
    sa.Column('artes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('livros_b')
    op.drop_table('livros_a')
    # ### end Alembic commands ###
